del .\*.ncb /f/s/q/a
del .\*.obj /f/s/q/a
del .\*.pdb /f/s/q/a
del .\*.ilk /f/s/q/a
del .\*.pch /f/s/q/a
del .\*.idb /f/s/q/a
del .\*.bsc /f/s/q/a
del .\*.user /f/s/q/a
del .\*.suo /f/s/q/a
del .\*.dep /f/s/q/a
del .\*.ipch /f/s/q/a
del .\*.sdf /f/s/q/a
del .\*.tlog /f/s/q/a
del .\*.timestamp /f/s/q/a
del .\*.meta /f/s/q/a
del .\*.manifest /f/s/q/a
del .\*.resources /f/s/q/a
del .\*.log /f/s/q/a
del .\*.lastbuildstate /f/s/q/a
del .\*.VC.db /f/s/q/a